SELECT ROOM_ID, AVG(GRADE) FROM 
DHASSID.GRADE NATURAL JOIN
(SELECT EXAM_ID, ROOM_ID FROM 
ROOMFORSTUDENTS NATURAL JOIN 
(SELECT *
FROM DHASSID.EXAM_ROOM NATURAL JOIN DHASSID.EXAM
WHERE DEP_ID = 1))
GROUP BY ROOM_ID
ORDER BY AVG(GRADE)
FETCH NEXT 3 ROWS ONLY
